### ISSUE TITLE
Proposed tags list for critical feedback.

### ISSUE THREAD

**Issue by kotp** [RubySteps/21-day-challenge#444]
Proposed {tag-request} style tag, as we can not add labels ourselves, even if they already exist..

**Comment by patmaddox** [comment]
I understand that you're okay with a blanket opt-in... it will be easier from a management perspective if you mention it in the pull requests. Something like:

"[TEARDOWN] your pull request subject..." and [TEARDOWN] indicates that you're okay with the code being torn down, by whoever.

This way we don't need to try to remember who has opted in, and who hasn't. As mentioned in [the Feedback wiki page](https://github.com/RubySteps/21-day-challenge/wiki/Feedback), "Critical feedback is opt-in only, _every time_".

And the nature of opt-in is such that the second checkbox isn't required :P

**Comment by patmaddox** [comment]
btw I would like to use this issue as a gathering place for proposing tags that people want to use? Then I can add them to the wiki.

People can just throw stuff out here... and I will also be on the lookout for any tags that people use in their pull requests, and add them here.

**Comment by kotp** [comment]
:movie_camera:  as a still frame photo :camera: may not catch this moving target.  But looks good to me. [lgtm]

**Comment by kotp** [comment]
Square tags may not work well either due to the markdown use.  Curly braces perhaps?  I stumbled upon this by accidentally providing a parenthesized statement directly afterward, which produces a HTML link... doh!

**Comment by kotp** [comment]
And as mentioned in Gitter... not sure I am liking the connotation of teardown as the mark to signal this.  We really are looking for clues and information to build up our code... {BUILDUP} is the final goal and so I think it is more appropriate.  Also the curly braces don't seem to interfere with anything.

**Comment by patmaddox** [comment]
TEARDOWN is just a thing I proposed :)  and [brackets] work just fine in the subject, where they belong (think email subject tagging / labeling...)

I suggest you just use whatever makes sense to you, and conventions will emerge... we don't need to define stuff upfront (that's how twitter #hashtags came about! people just started using them as a solution to their own problem)

**Comment by kotp** [comment]
So, git commit messages are appropriate then with the [BUILDUP] or {BUILDUP} on the first (or only) line.

Leaving 40 characters left for the expected (GUI Friendly) 50 character limit accounting for a space after the tag.

I am going to try that for my next PR.

**Comment by kotp** [comment]
No definitions going on, just discussions as to what is here.

**Comment by patmaddox** [comment]
I think you misunderstand... the tags / labels are not for commit messages. They're for pull requests.

When you submit a pull request, it has a subject. Put your desired tag there.

**Comment by kotp** [comment]
I misspoke,  It is the branch name that is used for the title/subject for the pull request, not a commit message.  And branch names don't have a 50 character utility limit as far as I know.  But then I don't use the GUI tools.  So I don't really keep up.

Of course the title can be changed if you are using the GUI button at that time.

**Comment by kotp** [comment]
Found out that square brackets are not allowed in branch names (not definitively, just per first test)... but curly brackets are.  So this should resolve my PR's to have the BUILDUP tag in them automatically.

**Comment by kotp** [comment]
https://github.com/RubySteps/21-day-challenge/pull/481 Successfully uses a branch name to indicate opt-in.

**Comment by patmaddox** [comment]
@kotp do you think this is sufficiently covered by the [feedback](https://github.com/RubySteps/21-day-challenge/wiki/Feedback) page on the wiki? I'd like to close this issue if we're done talking about it... and of course it can always get re-opened if we need

**Comment by kotp** [comment]
Like a dead horse, this has been sufficiently beaten.
