### ISSUE TITLE
Adventure 001 Retrospective

### ISSUE THREAD

**Issue by patmaddox** [RubySteps/21-day-challenge#512]
**This is a combined retrospective for Adventure 001** - so I don't forget to create a new retrospective each day :)
- What did you learn today?
- What would you like to do more of?
- What would you like to try?
- What's something new you did that you'd never done before?

**Comment by jbrains** [comment]
I'm glad that I have an excuse to try to do some desktop graphics stuff. Coming back to it with a different design sense has proven interesting. It doesn't take much to get tangled, but I feel less stuck than I probably did 10 years ago when I tried this last.

It's a shame, though, that desktop graphics libraries really haven't changed in 20 years. :tongue:

**Comment by jbrains** [comment]
Well, a surprise: the stuff I learned not-quite-writing an Android book helped me understand how to design stuff for GTK+. Yay.

**Comment by amaliahern** [comment]
Today I learnt how to implementate a hash map in ruby.
I would like to talk with other people and know of them.
I would like to try in Ruby at work
I had never try to do Roman Numerals data

hurray!!

**Comment by aniruddhabarapatre** [comment]
Built my first Sinatra app. Although nothing too fancy, just some basic routing and views.
Rails is too magic-ky for me, so need to know how all this works in barebones manner.

**Comment by patmaddox** [comment]
I am getting jealous watching other people's code, while feeling like I don't have the time and energy to work on my own interesting code. But we're two weeks in and I'm building up momentum! We'll see what happens...

**Comment by kimptoc** [comment]
Goal... my goal is to do a daily commit :)  Perhaps not too ambitious, but I believe already led to a little extra progress - my Chrome extension !  

PS @patmaddox , keeping this thing running is a major achievement on its own - well done!

**Comment by patmaddox** [comment]
@kimptoc awesome :) you don't need a big new goal... if "just" completing the challenge is your goal, then go for it!!

and thanks :) I am proud to have made it this far. I really want to get more of this automated over the next week so that future rounds won't be quite as much work for me. Because I started this one a week late in April, May's challenge will start the same day that April's ends!!

**Comment by amaliahern** [comment]
My goal is to get RDD, Readme Driven Development as you show me in http://tom.preston-werner.com/2010/08/23/readme-driven-development.html As Tom Preston-Werner said: "The Readme should be the single most important document in your codebase; writing it first is the proper thing to do."
Thanks @patmaddox for this incredible challenge. :-)

**Comment by tommycarney** [comment]
My goal is to program with more humans! 

Up to now, learning to program has been a solitary exercise. Last Monday I went to a Ruby co-learning event in Berlin, and it was great to talk with other people, and I even got some help from a expert when I got stuck.

If anyone here would like to give remote pair programming a go, just send me an email at tommycarney@gmail.com

**Comment by patmaddox** [comment]
@tommycarney awesome! if you can find a regular event to go to, definitely do it... and if you can't, maybe you can start one! There's a bi-weekly pair programming event in Los Angeles that was awesome - maybe you can get something going in Berlin.

I can't commit other people to stuff obviously, but I know that @kotp has been very generous in remote pairing with people for a long time now...

**Comment by patmaddox** [comment]
@amaliahern very cool! I am a huge fan of readme-driven development... I just don't do it enough! It's a great thing to practice, and one thing I like about this challenge.

In fact, I think for adventure 002 (which starts on Monday, same day that adventure 001 ends!) I may do exactly that - create a README for a new bit of software each day. Then at the end of 3 weeks I'll have a bunch of new project ideas, with the documentation already started...

**Comment by patmaddox** [comment]
How is everybody's GitHub streak? Has anyone set a new personal record (I have!!). I know @liamseanbrady mentioned something about keeping the streak going...

**Comment by kotp** [comment]
8 years of pair programming in Ruby.  Remote Pair programming since 1987.  Of course I do it a bit differently now, but still do it remotely.

**Comment by patmaddox** [comment]
I merged ~10 pull requests before running my quick checker... whoops! I hope I didn't merge stuff that I shouldn't have :)

**Comment by kotp** [comment]
Wow, I learned today that someone seems to have deleted the master branch... I came into the challenge, and was in 19th day branch, went to change branch to master.  It simply was not there.

To correct this, I did:

```
git branch # Found that master simply was not there.
git co master # confirmed that my eyes weren't deceiving me.
cat .git/config # verify that my git is exactly what I expect.
git fetch origin # fetch my origin on github (or wherever it is I store my remote repository)
git checkout origin/master # Checkout master in preparation
git checkout -b master # Create the master branch on my local repository
git fetch upstream master # grab the upstream changes.
git push origin master # update my origin with upstream changes.
```

Strange end and start of the challenge day!

**Comment by patmaddox** [comment]
@kotp just to confirm, that was an issue to your local machine, right? nothing weird on github... just an inadvertent "git branch -d master" on your end or something?

**Comment by kotp** [comment]
It may have been because of a pull from upstream yesterday that I simply did not notice until ready to todays work.  Or it could have been a combination of things that a cat walking across the keyboard could have done, as my machine was in a strange state when I woke up.  So very much unsure.

**Comment by kotp** [comment]
lol @ just an inadvertent `git branch -d master` but yes, a cat could have done that, but statistically, it is more likely that they would have completed the random sequence of `rm -rf .` instead.

Since I have not deleted local branches and have everything else here, and have never done a master deletion, it is not even in my shell history, accidentally doing this from my terminal is pretty unlikely, if it were a "history" invocation that I did not realize I did.

To confirm, it was only my local repository that did not have master.

**Comment by aniruddhabarapatre** [comment]
I am terrible with git, especially if it comes to branches and PR's.

**Comment by jbrains** [comment]
I have discovered that I can program, if needed, in Ruby, on my Android phone, as long as I have my trusty Logitech Bluetooth keyboard with me. I wouldn't want to do this under pressure, but I can do it. Yay for remote work!

**Comment by patmaddox** [comment]
@aniruddhabarapatre we all start off terrible at git! :)  Keep at it, it will click.

**Comment by patmaddox** [comment]
Well I think this one is sufficiently closed. Thanks for participating, everyone!

I promise I will update the heroes list!
