### ISSUE TITLE
Adventure 002 Retrospective

### ISSUE THREAD

**Issue by patmaddox** [RubySteps/21-day-challenge#863]
Adventure 002 is in progress!

**Comment by patmaddox** [comment]
Today I want to be on the lookout for for any questions or problems that people have.

For this challenge, I want to work on two things:
1. Automate some more of the checking & provide tools for people to verify their status in the challenge
2. Work on some software just for fun... maybe something around music?

**Comment by adeluccar** [comment]
My goal for this challenge is a humble one. 

I want to get back in the programming saddle. Up until a few months ago I was learning through tutorials and the like. Got bored. Dropped it on Christmas and never got back in. A 21 day challenge might help me with finding back the excitement I felt the first time I learned some programming concepts.
Overall goal is to prepare in a technical way for building a SAAS next year.

Today, I will focus on cramming some of my anki decks so I can get a quick head-start on what I've already learned. Revisit some of the main ruby constructs and lingo.

**Comment by cypher** [comment]
Since I managed to get in one day with code the last time, I'd like to make it to at least two this time ;)

**Comment by askl56** [comment]
I want to actually be involved in a group project if possible.

**Comment by adeluccar** [comment]
I really like how day 04 clinched the importance of sketching\* out code (or flowcharts) before actually coding. It made coding _so_ much easier afterwards.

*Real sketching in a notebook.

**Comment by kotp** [comment]
Hoping to work with @skahlert to update the countdown timer.

**Comment by adeluccar** [comment]
@kotp Just added a PR changing the date. Hope @skahlert can just approve and rebuild for rubygems to pickup. Works ok in my machine.

**Comment by kotp** [comment]
Did you add it as a possible dotfile?  I was going to work with him (or someone) and suggest a `.rubysteps` file in `$HOME` folder so that it is easily and externally changed.  I will check the PR.

**Comment by adeluccar** [comment]
No. I just changed the hardcoded date. Your approach seems feasible.

**Comment by patmaddox** [comment]
@adeluccar @kotp that sounds cool... although I'd suggest not using `~/.rubysteps` because I want to reserve it for stuff I make.

**Comment by kotp** [comment]
@patmaddox I was thinking about that, but if it is a standard format, perhaps a Hash, or even an external requirement like Yaml (But Hashes are so simple, not sure why people don't just use them for configurations) it should not really conflict.  Still if @skahlert can think of a more generic name, that would be better.

**Comment by adeluccar** [comment]
@kotp @patmaddox @skahlert 

##### Proposal for `.current_challenge` file

File should contain the following for the current running challenge:
1. Current challenge number.
2. Current challenge start date in a format ready for use with Ruby's Time libraries.
3. Same as before but with end date.

Example:

```
002
2015, 05, 04, 12, 0, 0, "+07:00"
2015, 05, 25, 11, 59, 0, "+7:00"
```

**Comment by adeluccar** [comment]
@kotp I agree with you on the usefulness of a hash for this particular use case. It makes it easier to inject the information in the plugins. The above could look like this also:

``` ruby
{ current: '002', start: '2015, 05, 04, 12, 0, 0, "+07:00"', end: '2015, 05, 25, 11, 59, 0, "+7:00"' }
```

**Comment by patmaddox** [comment]
for .rubysteps I'm planning on YAML and you could do something like:

``` yaml
github_username: patmaddox
challenge:
  - adventure: 002
  - start_date: 2015-05-04 12:00:00 -0600
```

Which is the basic structure I was planning on anyway.

@adeluccar @kotp where are you getting the +07:00 from? Ruby is telling me I'm -0600.

Also I like the default String format because Ruby parses it back out perfectly:

``` ruby
irb(main):002:0> Time.now
=> 2015-05-09 11:49:44 -0600
irb(main):003:0> Time.parse("2015-05-09 11:49:44 -0600")
=> 2015-05-09 11:49:44 -0600
```

Finally, at some point I'd like the date to not be hard-coded... you should be able to pull the adventure start date from rubysteps.com and maybe cache it locally. But that way you'd only ever need to update the adventure field.

**Comment by adeluccar** [comment]
@patmaddox Mountain Time observes -6:00 during daylight saving time (known as MDT) and -7:00 during autumn and winter (known as MST). Bet the ruby time libraries are aware of that. [Wikipedia](https://en.wikipedia.org/wiki/Mountain_Time_Zone)

**Comment by adeluccar** [comment]
@patmaddox Also, the +7 was a slip-up. Should have been -7 for the purposes of the example.

**Comment by kotp** [comment]
I wasn't thinking of a complex hash.  Was thinking like this:

```
RubySteps = {
  Iteration002: "2015-05-04 12:00:00 -0600",
 }
```

Wrapped as a module for `Projects` or whatever the naming convention would be.

This way you can track several projects, and it stays out of the way, especially if it is used for more than simply the counter.  When it comes back out, it is a simple string which is easy for the time methods.

Not sure why the parts were pulled out, thinking of parse while keeping it simple for humans would be a good goal.

**Comment by patmaddox** [comment]
if you guys use the format that I posted above, we won't run into conflicts w/ my stuff that uses `.rubysteps` ;)

**Comment by kotp** [comment]
I was thinking:

```
github_username: patmaddox
challenge:
  start: 2015-05-04 12:00:00.000000000 -06:00
  adventure: 002
```

Reduces the nested complexity.  Unless there is a reason for the array...

I would use a 'start' rather than "start_date", as it is not saying start_date_time_zone to be compltely forthright, so I think an all or none approach on that name/label.

**Comment by patmaddox** [comment]
@kotp maybe I'm reading yaml wrong but I think that's the same as what I posted? I admit I'm not 100% sure of the difference between a line beginning with - and one not...

**Comment by kotp** [comment]
Hopefully I copied these properly.

The dashes increase the structures complexity, introducing an array where we likely shouln't need to deal with one.

```
# With Dashes YAML and result
github_username: patmaddox
challenge:
  - adventure: 002
  - start_date: 2015-05-04 12:00:00 -0600

# hash produced

{
  "github_username"=>"patmaddox",
  "challenge"=>
  [
    {
      "adventure"=>2
    },
    {
      "start_date"=>2015-05-04 14:00:00 -0400
    }
  ]
}

# Simple YAML and result
github_username: patmaddox
  challenge:
  adventure: 002
  start_date: 2015-05-04 12:00:00 -0600

# hash produced

{
  "github_username"=>"KOTP",
  "challenge"=>
  {
    "adventure"=>2,
    "start_date"=>2015-05-04 14:00:00 -0400
  }
}
```

**Comment by patmaddox** [comment]
oh. yeah, I definitely don't want that ugly array in there! the simple hash is what we want.

whatever the correct YAML is to produce it, :+1:

**Comment by kotp** [comment]
I should note though that I missed the quotes that should be around the 002 like this: `"002"` due to wanting to indicate to the editor of the config file that we really are interested in leading zeros.

**Comment by kotp** [comment]
I understand why people use YAML for configurations, but I generally put it off as long as possible, and prefer to use a Hash.  The meaning is more clear, and translations are simply not there.  But as soon as other tools start touching the configuration file then YAML or another 'simpified' configuration standard is pretty much called for.

So as long as possible, Ruby is my configuration tool. :)

**Comment by patmaddox** [comment]
YAML is pretty standard for configuration files in the Ruby world.

In any case, if you use `.rubysteps` (which I would really like!) then it should be a YAML file formatted like:

``` yaml
github_username: patmaddox
challenge:
  adventure: 2
  start_date: 2015-05-04 12:00:00 -0600
```

Because that's what I'm going to use :)

Of course if you use a different file name, structure it however you want!

Note: the adventure field doesn't need to be a string... I just use `002` in the directory name so that it will sort nicely on systems that aren't smart enough to know that 12 is greater than 1. When comparing to filenames on disk we can use sprintf to get a 3-digit representation of it padded with zeros:

``` ruby
sprintf("%03d", 2) # => "002"
```

**Comment by adeluccar** [comment]
@patmaddox A quick related note though, if you keep the `-06:00`, you will likely have a conflict when Mountain Time changes from MDT (Mountain Daylight) to (Mountain Standard) which is -07:00 for challenges set in winter. 

Maybe there's a way of specifying the actual time zone and let ruby deal with it?

**Comment by kotp** [comment]
This is a good argument to use someone else's time zone, like Arizona, where they don't believe in such things as biannual termporal disturbances.

**Comment by kotp** [comment]
I did notice that yaml seems to detect date objects as well, and converts them to local time, at least when I do convert from yaml to hash back to yaml, the time zone ended up becoming local, with no further steps from me between actions (I directly chained the methods to see.).

**Comment by patmaddox** [comment]
@adeluccar that's a good point... although I suspect by the time we get there, I can have a simple endpoint on rubysteps.com which addresses that problem.

I _could_ even do that today! It shouldn't be hard...

**Comment by patmaddox** [comment]
What do people think of the daily reminder emails? I'm not so sure anybody reads them after week 1 :)

**Comment by kotp** [comment]
I read them every day.

**Comment by adeluccar** [comment]
@patmaddox I also read the emails. If anything, I would advise to be more specific on what do you want people to accomplish. By that I mean, the emails feel a bit nebulous action-wise. Maybe try an approach more like "This is how I play X game... so now, you get to play it. This time, you will find a repo on github and look for a way of adding a pull request to the documentation of that repo."? Don't get me wrong though, I believe your open-ended approach is quite cool, but at the same time, I could use some more structure. Hope the feedback helps.

**Comment by patmaddox** [comment]
@adeluccar I want people to do the same thing every day - create a readme and send a pull request. The emails are a bit nebulous action-wise because I'm not trying to get you to do anything new.

They're just a reminder and motivation, really. I could just as easily say: "The 21 day challenge starts now! Send your pull requests each day" and leave it at that.

It's a simple game, and sometimes simple things like this can be difficult to grasp at first. But creating a readme and sending a pull request each day is all there is to it, really :)

**Comment by kotp** [comment]
The lack of e-mail reminders was not really a problem for me, but I do use others pull requests as a reminder as well.  Pat's day 20 pull reminded me that I had not done the day 20 early on as I usually have been doing.  So I got to do a "last 5 minute" PR and a "first 5 minute" PR for day 20 and 21.

**Comment by patmaddox** [comment]
Thanks for playing, everyone! That was fun :)
