### ISSUE TITLE
Why when I pull upstream (here) there is a raven folder?

### ISSUE THREAD

**Issue by kotp** [RubySteps/21-day-challenge#99]
I think a pull request got through. :)

It is at `./raven`

**Comment by kotp** [comment]
This is a continuation of #56 I believe.

Remember to do a `git rm -r raven` to recursively remove and stage that removal and then a `git commit` or a `git commit -v`  to commit the deletions.

I like using -v for my commits as I can verify what I think is happening is happening while I am writing a detailed commit message.

**Comment by patmaddox** [comment]
@ravencovington would you like to take care of this? :)

**Comment by ravencovington** [comment]
My apologies. Fixed and sent in a PR.

**Comment by patmaddox** [comment]
@kotp I think it should be good... but since you're the one that brought it up, please confirm that this issue is now fixed :)
